### ISSUE TITLE
The :ReadGradeOn command fails with the “This Vim cannot execute :python after using :py3” message

### ISSUE THREAD

**Issue by jhradilek** [pondrejk/vim-readability#1]
After installing both the [textstat](https://pypi.python.org/pypi/textstat/) package and the [vim-readability](https://github.com/pondrejk/vim-readability) plug-in, an attempt to run the `:ReadGradeOn` command causes Vim to print the following error message:

```
Error detected while processing function ReadGradeEnable..PlaceLoop..FleschKincaidGrade:
line   23:
E836: This Vim cannot execute :python after using :py3
E263: Sorry, this command is disabled, the Python library could not be loaded.
Error detected while processing function ReadGradeEnable..PlaceLoop:
line    3:
E121: Undefined variable: g:funreturn
E15: Invalid expression: g:funreturn
line    5:
E121: Undefined variable: grade
E15: Invalid expression: grade != 0
Press ENTER or type command to continue 
```

I am using **Vim version 7.4.827** with a rather large number of additional plug-ins so there is a chance that they interfere with each other. I also have both **Python 2.7.8** (the `python` executable) and **Python 3.4.1** (`python3`) installed in the system.

**Comment by jhradilek** [comment]
After taking a closer look at the error message, I was able to figure out what the problem is. In Fedora and I believe in Debian too, Vim is built with support for both Python 2 and 3:

```
$ vim --version | grep -oe '[+-]python[^ ]\+'
+python/dyn
+python3/dyn
```

The problem is that to do so, it relies on dynamic loading of libraries for Python and in one session, it cannot possibly load libraries for both versions at the same time. Unfortunately, this means that which version your session ends up using largely depends on the combination of plug-ins you use. Or in other words, the first plug-in that loads Python makes the choice for all other plug-ins. In my case, it is Python 3:

```
:echo has("python")
0
:echo has("python3")
1
```

I looked at your code and it would not be difficult to rewrite it to support both versions of Python; many other plug-ins seem to do so. Sadly, I don't think the **textstat** package is officially available for Python 3 and even though I was able to make it work on my system, the change is not that trivial. If you want, I can document my workaround for you but for now, could you at least add a piece of code to verify which version is supported in the current session and report a user-friendly error if it is not Python 2?

**Comment by pondrejk** [comment]
see commit  [6defbd2d2d428867976ff5d5eb2c9e26563314a1](https://github.com/pondrejk/vim-readability/commit/6defbd2d2d428867976ff5d5eb2c9e26563314a1)
